import setuptools

setuptools.setup(
    name='django-access-logger',
    version='0.4.3',
    description='Access logging for Django, the right way',
    author="Dreem",
    author_email="luc@dreem.com",
    url="https://github.com/Dreem-Organization/django-access-logger",
    license='Apache2',
    packages=setuptools.find_packages(),
    zip_safe=False,
    install_requires=[],
    include_package_data=True,
    classifiers=[
        'Environment :: Web Environment',
        'Intended Audience :: Developers',
        'Development Status :: 4 - Beta',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: Utilities',
        'Framework :: Django',
        'Topic :: Internet :: WWW/HTTP :: WSGI :: Middleware',
        'Topic :: System :: Logging',
    ],
)
